routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('guest')->get('/', function () {
    return redirect()->route('login');
});

Auth::routes([
    'register' => false,
    'reset' => false
]);

Route::group([
    'middleware' => 'auth'
], function () {
    Route::get('/home/{category?}', 'HomeController')->name('home');

    Route::resource('/books', 'BookController', [
        'except' => ['index', 'show']
    ]);

    Route::get('/books/{book}', 'BookController@destroy')->name('book.destroy');

    Route::resource('/categoies', 'CategoryController', [
        'except' => ['show', 'create']
    ]);
});

app/Book.php
<?php

namespace App;

use App\Traits\Fillable;
use App\Traits\Filterable;
use App\Traits\Searchable;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use Fillable, Filterable, Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'author', 'price', 'medium', 'image',
        'isbn', 'published_at', 'category_id', 'description'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'published_at' => 'date:Y-m-d',
    ];

    /**
     * The relationships to always eager-load.
     *
     * @var array
     */
    protected $with = ['category'];

    /**
     * Get the books cover image.
     *
     * @param string $value
     *
     * @return string
     */
    public function getImageAttribute($value)
    {
        if (Str::contains($value, 'http')) {
            return $value;
        }

        return asset($value ?: 'img/book.png');
    }

    /**
     * Set the books's price in cents.
     *
     * @param string $value
     * @return string
     */
    public function setPriceAttribute($value)
    {
        $this->attributes['price'] = $value * 100;
    }

    /**
     * Get the books's price.
     *
     * @param  string  $value
     * @return string
     */
    public function getPriceAttribute($value)
    {
        return $value / 100;
    }

    /**
     * Get the category details this book belongs to.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Category;
use App\Http\Requests\Book as BookForm;

class BookController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('books.create', [
            'book' => new Book,
            'categories' => Category::all()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        return view('books.edit', [
            'book' => $book,
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Book  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookForm $request)
    {
        Book::create($this->attributes($request));

        return success(route('home'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Book  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(BookForm $request, Book $book)
    {
        $book->update($this->attributes($request));

        return success(route('home'), 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        $book->delete();

        return success(route('home'), 'deleted');
    }

    /**
     * Get only mass assignable attributes from request object.
     *
     * @param  \App\Http\Requests\Book $request
     * @return array
     */
    protected function attributes($request)
    {
        if (is_null($request->image)) {
            return $request->except('image');
        }

        return array_merge(
            $request->only(Book::attributes()),
            ['image' => $request->file('image')->store('img', 'public')]
        );
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="py-12 bg-gray-800">
        <div class="container">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9">
                        Add New Book
                    </h2>

                    <div class="mt-1 flex flex-col sm:mt-0 sm:flex-row sm:flex-wrap">
                        <div class="mt-2 flex items-center text-gray-500 font-semibold sm:mr-6">
                            Filling in the all the information will create a new book entry in the database.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <form action="{{ route('books.store') }}" method="POST" class="py-12" enctype="multipart/form-data">
        @csrf

        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-6 md:mb-0">
                    <h4 class="text-xl font-semibold">
                        Book Details
                    </h4>

                    <p class="text-sm text-gray-500 max-w-sm">
                        This information will be displayed publicly to the customer and will be used for sorting.
                    </p>
                </div>

                <div class="col-md-8 mb-6 md:mb-0">
                    <div class="bg-white px-4 py-5 sm:px-6 rounded-lg shadow mb-6">
                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="name" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Name of book') }}</span>

                                    <input id="name" type="text" class="form-input mt-1 block w-full @error('name') is-invalid @enderror" name="name" value="{{ old('name') ?? ($book->name ?? null) }}" required autocomplete="name" placeholder="Ex. Everything I Never Told You">
                                </label>

                                @error('name')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="image">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Image') }}</span>

                                    <input type="file" class="w-full block mt-1" name="image" id="image">
                                </label>

                                @error('image')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="author" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Author') }}</span>

                                    <input id="author" type="text" class="form-input mt-1 block w-full @error('author') is-invalid @enderror" name="author" value="{{ old('author') ?? ($book->author ?? null) }}" required autocomplete="author" placeholder="Celeste Ng">
                                </label>

                                @error('author')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="price" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Price ($)') }}</span>

                                    <input id="price" type="text" class="form-input mt-1 block w-full @error('price') is-invalid @enderror" name="price" value="{{ old('price') ?? ($book->price / 100 ?? null) }}" required autocomplete="price" placeholder="6.99">
                                </label>

                                @error('price')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Medium') }}</span>

                                    <select name="medium" id="medium" class="form-select mt-1 block w-full">
                                        <option value="Sinhala" selected>Sinhala</option>
                                        <option value="English">English</option>
                                        <option value="Tamil">Tamil</option>
                                    </select>
                                </label>

                                @error('medium')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="isbn" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('ISBN') }}</span>

                                    <input id="isbn" type="text" class="form-input mt-1 block w-full @error('isbn') is-invalid @enderror" name="isbn" value="{{ old('isbn') ?? ($book->isbn ?? null) }}" required autocomplete="isbn" placeholder="9783161484100">
                                </label>

                                @error('isbn')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="published_at" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Published on') }}</span>

                                    <input id="published_at" type="text" min="13" class="form-input date_picker mt-1 block w-full @error('published_at') is-invalid @enderror" name="published_at" value="{{ old('published_at') ?? ($book->published_at ?? null) }}" required autocomplete="published_at" placeholder="{{ now()->format('M j, Y') }}">
                                </label>

                                @error('published_at')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Category') }}</span>

                                    <select name="category_id" id="category_id" class="form-select mt-1 block w-full">
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </label>

                                @error('category_id')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-end items-center">
                        <a href="{{ route('home') }}" class="btn bg-white text-gray-800 hover:bg-indigo-100 hover:text-gray-800 focus:bg-indigo-100 focus:text-gray-800" data-dismiss="modal">Cancel</a>

                        <button class="btn ml-3" type="submit">Add book</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="py-12 bg-gray-800">
        <div class="container">
            <div class="lg:flex lg:items-center lg:justify-between">
                <div class="flex-1 min-w-0">
                    <h2 class="text-2xl font-bold leading-7 text-white sm:text-3xl sm:leading-9">
                        Edit Details
                    </h2>

                    <div class="mt-1 flex flex-col sm:mt-0 sm:flex-row sm:flex-wrap">
                        <div class="mt-2 flex items-center text-gray-500 font-semibold sm:mr-6">
                            You are about to edit the details of a book.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <form action="{{ route('books.update', ['book' => $book->id]) }}" method="POST" class="py-12" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="container">
            <div class="row">
                <div class="col-md-4 mb-6 md:mb-0">
                    <h4 class="text-xl font-semibold">
                        Book Details
                    </h4>

                    <p class="text-sm text-gray-500 max-w-sm">
                        This information will be displayed publicly to the customer and will be used for sorting.
                    </p>
                </div>

                <div class="col-md-8 mb-6 md:mb-0">
                    <div class="bg-white px-4 py-5 sm:px-6 rounded-lg shadow mb-6">
                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="name" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Name of book') }}</span>

                                    <input id="name" type="text" class="form-input mt-1 block w-full @error('name') is-invalid @enderror" name="name" value="{{ old('name') ?? ($book->name ?? null) }}" required autocomplete="name" placeholder="Ex. Everything I Never Told You">
                                </label>

                                @error('name')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="image">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Image') }}</span>

                                    <input type="file" class="w-full block mt-1" name="image" id="image">
                                </label>

                                @error('image')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="author" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Author') }}</span>

                                    <input id="author" type="text" class="form-input mt-1 block w-full @error('author') is-invalid @enderror" name="author" value="{{ old('author') ?? ($book->author ?? null) }}" required autocomplete="author" placeholder="Celeste Ng">
                                </label>

                                @error('author')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="price" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Price ($)') }}</span>

                                    <input id="price" type="text" class="form-input mt-1 block w-full @error('price') is-invalid @enderror" name="price" value="{{ old('price') ?? ($book->price ?? null) }}" required autocomplete="price" placeholder="6.99">
                                </label>

                                @error('price')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Medium') }}</span>

                                    <select name="medium" id="medium" class="form-select mt-1 block w-full">
                                        <option value="Sinhala" selected>Sinhala</option>
                                        <option value="English">English</option>
                                        <option value="Tamil">Tamil</option>
                                    </select>
                                </label>

                                @error('medium')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label for="isbn" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('ISBN') }}</span>

                                    <input id="isbn" type="text" class="form-input mt-1 block w-full @error('isbn') is-invalid @enderror" name="isbn" value="{{ old('isbn') ?? ($book->isbn ?? null) }}" required autocomplete="isbn" placeholder="9783161484100">
                                </label>

                                @error('isbn')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="published_at" class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Published on') }}</span>

                                    <input id="published_at" type="text" min="13" class="form-input date_picker mt-1 block w-full @error('published_at') is-invalid @enderror" name="published_at" value="{{ old('published_at') ?? ($book->published_at ?? null) }}" required autocomplete="published_at" placeholder="{{ now()->format('M j, Y') }}">
                                </label>

                                @error('published_at')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-6 mb-6">
                                <label class="block">
                                    <span class="text-sm mb-2 font-semibold">{{ __('Category') }}</span>

                                    <select name="category_id" id="category_id" class="form-select mt-1 block w-full">
                                        @foreach ($categories as $category)
                                            <option @if ($book->category->id == $category->id) selected @endif value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </label>

                                @error('category_id')
                                    <span class="text-sm block mt-2 text-red-500" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="flex justify-end items-center">
                        <a href="{{ route('home') }}" class="btn bg-white text-gray-800 hover:bg-indigo-100 hover:text-gray-800 focus:bg-indigo-100 focus:text-gray-800" data-dismiss="modal">Cancel</a>

                        <button class="btn ml-3" type="submit">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection